# -*- coding: utf-8 -*-
"""Churn Modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxfTdBCq1Ip9mFYgjBQaAsXc3GRtMf9N
"""

from google.colab import files

# This will open a file picker dialog
uploaded = files.upload()

import pandas as pd

# Load the file into a DataFrame
df = pd.read_csv("Churn_Modelling.csv")
df.head()



"""Clean & Prepare Your Churn Data in Colab

"""

df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

""" Step 2: Encode Categorical Columns"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

df = pd.get_dummies(df, columns=['Geography'], drop_first=True)



"""Check the Cleaned Data"""

df.head()

"""Check for Null or Missing Values"""

# Check for any missing (null) values
df.isnull().sum()

df.info()

print(df.columns)

france_rows = df[(df['Geography_Germany'] == 0) & (df['Geography_Spain'] == 0)]
print(france_rows.shape)
france_rows.head()

"""Logistic Regression for Churn Prediction"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

"""Split your data into features and target"""

X = df.drop('Exited', axis=1)  # all features
y = df['Exited']               # target

""" Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Train Logistic Regression model"""

model = LogisticRegression(max_iter=1000)  # increase max_iter for convergence
model.fit(X_train, y_train)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

"""Train the Model with Scaled Data"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)  # Ensures it has enough iterations to converge
model.fit(X_train_scaled, y_train)

""" Make Predictions on Test Data"""

y_pred = model.predict(X_test_scaled)
y_pred

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n🔍 Classification Report:\n", classification_report(y_test, y_pred))
print("\n🧮 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

coefficients = pd.DataFrame(model.coef_[0], index=X.columns, columns=['Coefficient'])
coefficients = coefficients.sort_values(by='Coefficient', ascending=False)
print(coefficients)

"""AGE --EXIT"""

age_churn = df.groupby(['Age', 'Exited']).size().unstack().fillna(0)
age_churn.columns = ['Stayed', 'Churned']
age_churn.head()

import matplotlib.pyplot as plt

age_churn.plot(kind='bar', stacked=True, figsize=(15, 6), colormap='viridis')
plt.title('Customer Churn by Age')
plt.xlabel('Age')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45)
plt.legend(title='Exited')
plt.tight_layout()
plt.show()

age_churn = df.groupby(['Gender', 'Exited']).size().unstack().fillna(0)
age_churn.columns = ['Gender', 'Churned']
age_churn

import matplotlib.pyplot as plt

age_churn.plot(kind='bar', stacked=True, figsize=(15, 6), colormap='viridis')
plt.title('Customer Churn by Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45)
plt.legend(title='Exited')
plt.tight_layout()
plt.show()